//
// Created by Administrator on 2016/11/21.
//

#ifndef NDK01APPLICATION_COM_NDKDEMO_NATIVEHELPER_H
#define NDK01APPLICATION_COM_NDKDEMO_NATIVEHELPER_H

#endif //NDK01APPLICATION_COM_NDKDEMO_NATIVEHELPER_H
